# Generated by Django 3.1.5 on 2021-01-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('watch', models.IntegerField()),
                ('negative_keyword', models.ManyToManyField(related_name='negative_keyword', to='reviewzip.Keyword')),
                ('negative_sentence', models.ManyToManyField(related_name='negative_sentence', to='reviewzip.Sentence')),
                ('positive_keyword', models.ManyToManyField(related_name='positive_keyword', to='reviewzip.Keyword')),
                ('positive_sentence', models.ManyToManyField(related_name='positive_sentence', to='reviewzip.Sentence')),
            ],
        ),
    ]
