# Generated by Django 3.1.6 on 2021-02-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewinfo',
            name='file',
        ),
        migrations.AddField(
            model_name='reviewinfo',
            name='file_path',
            field=models.FilePathField(null=True, path='review_files/'),
        ),
        migrations.AlterField(
            model_name='reviewinfo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
