# Generated by Django 3.1.6 on 2021-02-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0002_auto_20210209_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinfo',
            name='file_path',
            field=models.FilePathField(null=True, path='C:\\projects\\reviewproject\\review_files'),
        ),
    ]
