# Generated by Django 3.1.6 on 2021-02-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0003_auto_20210213_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinfo',
            name='file_path',
            field=models.FilePathField(null=True, path='review_files/'),
        ),
    ]
