# Generated by Django 3.1.5 on 2021-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0003_auto_20210131_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='negative_keyword',
            field=models.ManyToManyField(blank=True, related_name='negative_keyword', to='reviewzip.Keyword'),
        ),
        migrations.AlterField(
            model_name='review',
            name='negative_sentence',
            field=models.ManyToManyField(blank=True, related_name='negative_sentence', to='reviewzip.Sentence'),
        ),
        migrations.AlterField(
            model_name='review',
            name='positive_keyword',
            field=models.ManyToManyField(blank=True, related_name='positive_keyword', to='reviewzip.Keyword'),
        ),
        migrations.AlterField(
            model_name='review',
            name='positive_sentence',
            field=models.ManyToManyField(blank=True, related_name='positive_sentence', to='reviewzip.Sentence'),
        ),
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
