# Generated by Django 3.1.5 on 2021-02-03 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0004_auto_20210203_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingurl',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
