# Generated by Django 3.1.6 on 2021-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0004_auto_20210213_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinfo',
            name='file_path',
            field=models.FilePathField(default='15.csv', path='review_files/'),
            preserve_default=False,
        ),
    ]
