# Generated by Django 3.1.5 on 2021-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0005_pendingurl_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='csv',
            field=models.FileField(null=True, upload_to='review_files/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
