# Generated by Django 3.1.5 on 2021-02-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0005_pendingurl_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='review_files/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
