# Generated by Django 3.1.6 on 2021-02-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0006_auto_20210214_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
