# Generated by Django 3.1.5 on 2021-02-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0006_auto_20210204_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewfile',
            old_name='name',
            new_name='file',
        ),
    ]
