# Generated by Django 3.1.5 on 2021-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0006_auto_20210203_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='review_files/'),
        ),
    ]
