# Generated by Django 3.1.5 on 2021-02-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0007_auto_20210204_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfile',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
