# Generated by Django 3.1.5 on 2021-02-04 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0008_reviewfile_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
