# Generated by Django 3.1.6 on 2021-02-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewzip', '0010_keyword_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
